apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: my-apache-app
        image: 09eb771a8240  
        resources:
          requests:
            cpu: 10m
